### ISSUE TITLE
暫く起動しっぱなしにしているとチャートが正しく表示されなくなります。

### ISSUE THREAD

**Issue by kazu2go** [torum/BitWallpaper#6]
![ウィジェット](https://user-images.githubusercontent.com/96111206/145966772-91f94fb7-9398-4c9a-9425-629ac38f57a9.jpg)

添付画像の通りです。

暫く起動しっぱなしにしているとチャートが正しく表示されなくなり
再起動すると改善します。

毎日再起動しています。

改善できたら助かります。

**Comment by torum** [comment]
大変遅くなりまして申し訳ありません。ご不便をおかけしてしましました。この度、一からすべて設計し直し、作り直したので、新しいバージョンをお試しいただければと思います。まだまだ機能が足りないのですが、おいおい追加して更新していきたいと思います。
